[project]
name = "oronyx"
version = "3.1.0"
requires-python = ">=3.10"
description = "Easy to read English scheduling. Like Cron, but for humans."
authors = [
    {name = "Taira", email = "tairabiteru@users.noreply.github.com"}
]
dependencies = [
    "astronomy-engine"
]